### ISSUE TITLE
Error with a Neovim nightly built-in completion

### ISSUE THREAD

**Issue by kristijanhusak** [yioneko/vtsls#164] opened 2024-06-05 17:50 UTC
Hi, I'm testing new Neovim builtin lsp completion (https://neovim.io/doc/user/lsp.html#vim.lsp.completion.enable()) and I'm getting some errors when I confirm the selection. It seems that JSON that is being sent is invalid on `labelDetails`.

Here are steps to reproduce:

1. Create `minimal_init.lua` file with this content:
```lua
local tmp_dir = vim.env.TMPDIR or vim.env.TMP or vim.env.TEMP or '/tmp'
local nvim_root = tmp_dir .. '/nvim_vtsls'
local lazy_root = nvim_root .. '/lazy'
local lazypath = lazy_root .. '/lazy.nvim'

-- Install lazy.nvim if not already installed
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'neovim/nvim-lspconfig',
    dependencies = {
      { 'yioneko/nvim-vtsls' },
      { 'williamboman/mason.nvim' },
    },
    config = function()
      require('mason').setup({
        install_root_dir = nvim_root..'/mason',
        log_level = vim.log.levels.TRACE
      })
      require('lspconfig').vtsls.setup({
        on_attach = function(client, bufnr)
          vim.lsp.completion.enable(true, client.id, bufnr, { autotrigger = true })
          vim.lsp.set_log_level(vim.lsp.log_levels.TRACE)
        end
      })
    end,
  },
}, {
  root = lazy_root,
  lockfile = nvim_root .. '/lazy.json',
  install = {
    missing = true,
  },
})

require('lazy').sync({
  wait = true,
  show = false,
})
```
2.  Make sure you have latest nightly version of Neovim. I use [bob](https://github.com/MordechaiHadad/bob) to achieve that: `bob use nightly`
3. Create a test typescript file: `echo "const test = { hello: 'world' }" > init.ts`
4. Open up neovim with the minimal init: `nvim -u minimal_init.lua`
5. Once the lazy finishes installing, install vtsls with mason: `:MasonInstall vtsls`
6. Once vtsls is installed, open up the ts file: `:edit init.ts`
7. On new line, try writing `test.`, autocompletion should automatically show
8. Select the only entry in the autocompletion and press `<C-y>` to accept it
9. See the error:
![screenshot_2024_06_05_19_44_00](https://github.com/yioneko/vtsls/assets/1782860/c86dab9b-83bc-4fdb-9b78-4ca80327757e)

I checked why it can't encode the JSON, and it turns out there is a `labelDetails` object where key is `true`: This is what is in lsp log:

```lua
{
    command = {
      arguments = { { cacheId = 3, index = 0, providerId = 2 } },
      command = '_vtsls.completionCacheCommand',
      title = '',
    },
    commitCharacters = { '.', ',', ';', '(' },
    data = { cacheId = 3, index = 0, providerId = 2 },
    filterText = '.hello',
    insertText = '.hello',
    insertTextFormat = 1,
    kind = 5,
    label = 'hello',
    labelDetails = { [true] = 6 },
    sortText = '11',
    textEdit = {
      newText = '.hello',
      range = {
        ['end'] = { character = 5, line = 2 },
        start = { character = 4, line = 2 },
      },
    },
  }
```

When you try to do `vim.json.encode` on it, it errors out. Once the `labelDetails` is removed, it works.

Just to note that I don't have any issues with vtsls with cmp.

Also, I'm not 100% sure if this is issue with `vtsls` or Microsoft's `tsserver`, but I confirmed that I don't have this issue with `typescript-language-server`.

**Comment by yioneko** [comment] 2024-06-06 02:12
I could reproduce the error but I suspect this is not a problem on server side. The invalid field `labelDetails = { [true] = 6 }` is sent during a `completionItem/resolve` request, while I notice the corresponding item in `textDocument/completion` response has field `labelDetails = vim.empty_dict()`, which means that the completion response from server side is valid and deserialized by client correctly. For reference, [`labelDetails` fields could be optional in spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemLabelDetails).

It seems that new builtin completion has problem with an empty object as a field of completion item. And I guess `typescript-language-server` does not have the same problem because it does not set `labelDetails` field if the client does not support it or the server does not support `labelDetails` at all.

**Comment by kristijanhusak** [comment] 2024-06-11 07:53
I opened up the issue on Neovim.
Is there a way to temporarily disable these labelDetails through the attach function?

**Comment by yioneko** [comment] 2024-06-11 09:06
Here is one possible workaround:
```lua
vim.api.nvim_create_autocmd("CompleteDonePre", {
  callback = function()
    local item = vim.v.completed_item
    if item and vim.tbl_get(item, "user_data", "nvim", "lsp", "completion_item", "labelDetails") then
      item.user_data.nvim.lsp.completion_item.labelDetails = nil
      vim.v.completed_item = item
    end
  end,
})
```
You can also try to override `vim.lsp.hanlders[vim.lsp.protocol.Methods.textDocument_completion]`.

**Comment by yioneko** [comment] 2024-06-11 11:29
I found that there are still some problems while testing nvim builtin completion, which might be useful to you.

**Some completion items are missing**: this is the problem on server side, and should be fixed in https://github.com/yioneko/vtsls/commit/f0beac03e90531ea17d37a134d4af83c94132b2c (not released yet).

**Manually triggered completion yields many items unrelated to typed prefix**:

This is due to that the client only uses `filterText` to do filtering:
https://github.com/neovim/neovim/blob/d8e384b7bfd5829e5ff5006202faa584b3211e84/runtime/lua/vim/lsp/completion.lua#L241-L244

While this is how the spec describe `filterText`:
> A string that should be used when filtering a set of completion items. **When omitted the label is used as the  filter text** for this item.

Currently only a few items from response have `filterText` set and we expect the client to use `label` for filtering in such case. You can work around this by manually setting `label` to `filterText` in `CompleteDonePre` event similar to the code I posted in the previous comments.

**Comment by kristijanhusak** [comment] 2024-06-11 15:36
Thanks, the workaround works great!

> Manually triggered completion yields many items unrelated to typed prefix:

> This is due to that the client only uses filterText to do filtering:
[neovim/neovim@d8e384b/runtime/lua/vim/lsp/completion.lua#L241-L244](https://github.com/neovim/neovim/blob/d8e384b7bfd5829e5ff5006202faa584b3211e84/runtime/lua/vim/lsp/completion.lua#L241-L244)

> While this is how the spec describe filterText:

> A string that should be used when filtering a set of completion items. When omitted the label is used as the filter text for this item.

Yeah, I noticed this, but I thought I'm not understanding the LSP spec. I'll open up a separate issue for that, thanks!

If you want we can close this, since the issue is not in here.

**Comment by yioneko** [comment] 2024-06-12 03:06
Then let's close this for now. If you found any further problems, feel free to raise another issue.

**Closed by yioneko** 2024-06-12 03:06 UTC
